id: P007899
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4776
  title: སེར་སྨད་ཟུར་བཀོལ
  author: ''
  volumes:
    039f71934d664bfd86d385243b8b1710:
      image_group_id: I1KG4828
      title: ''
      volume_number: 1
      total_pages: 472
    e03ec8b0afd74b30a0347029525f93eb:
      image_group_id: I1KG4829
      title: ''
      volume_number: 2
      total_pages: 316
ebook_metadata:
  title: སེར་སྨད་ཟུར་བཀོལ
  author: ''
  sku: P007899
  cover: cover.jpg
  layers:
  - pagination
