id: P007899
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG4776
  title: སེར་སྨད་ཟུར་བཀོལ
  author: ''
  volumes:
    3fc4951cb0214c32b385d7f85caf484d:
      image_group_id: I1KG4828
      title: Volume 1 of ser smad zur bkol
      volume_number: 1
      total_pages: 472
      base_file: v001.txt
    1cd28328338d48ffbd00e26a73f350ef:
      image_group_id: I1KG4829
      title: Volume 2 of ser smad zur bkol
      volume_number: 2
      total_pages: 316
      base_file: v002.txt
