id: IC3D50422
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:30:30+00:00'
last_modified: '2022-06-09T07:13:59.863166+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4776
  title: སེར་སྨད་ཟུར་བཀོལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4F77:
      image_group_id: I1KG4828
      title: Volume 1 of ser smad zur bkol
      total_pages: 472
      order: 1
      base_file: 4F77.txt
    F566:
      image_group_id: I1KG4829
      title: Volume 2 of ser smad zur bkol
      total_pages: 316
      order: 2
      base_file: F566.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
