id: IC3D50422
legacy_id: P007899
ocr_import_info:
  bdrc_scan_id: W1KG4776
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T11:28:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:47:21.638950+00:00'
last_modified: 2022-09-01 00:47:45.967664
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4776
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4776
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སེར་སྨད་ཟུར་བཀོལ།
  author: ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9464562601370943
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG4828:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4828
      total_pages: 472
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG4828.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9418744019145834
    legacy_id: v001
  I1KG4829:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG4829
      total_pages: 316
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG4829.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9545358713379666
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
